version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
  web-app:
    build:
      context: ./web-app
    container_name: web-app
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
  ml-client:
    build:
      context: ./machine-learning-client
    container_name: ml-client
    expose:
      - 5000
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017