version: '3.8'

services:
  mangodb:
    image: mongo:latest
    container_name: mangodb
  web-app:
    build:
      context: ./web-app
    container_name: web-app
    ports:
      - "5001:5000"
    depends_on:
      - mangodb
    environment:
      - MANGO_URI=mangodb://mangodb:27017
  ml-client:
    build:
      context: ./machine-learning-client
    container_name: ml-client
    depends_on:
      - mangodb
    environment:
      - MANGO_URI=mangodb://mangodb:27017
