name: CI / CD
on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.11"]
      
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Turn on 'editable' mode
        working-directory: ./machine-learning-client 
        run: |
          pipenv install -e .
      - name: Test with pytest
        working-directory: ./machine-learning-client 
        run: |
          pipenv run python -m pytest